version: '3.8'

services:
  redis:
    image: redis:8.6.1
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./logs:/var/log/redis
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    networks:
      - redis-network

  redis-commander:
    image: rediscommander/redis-commander:redis-commander-210
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - TZ=Asia/Shanghai
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge